# Generated by Django 3.2.15 on 2023-07-19 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20230719_2213'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
